-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgwYH6eOtJDnlerrR/
f2i4daSf38kahJjlj4MOHyOvgVSgCgYIKoZIzj0DAQehRANCAAShxjiwmi8XHcIY
eY5kAjbnWZx9u+hUQulIuEu1Ox/LrNwnbHLTiSPV/BopuzdEWu+kaqDmK90GPnBo
2TsKNPbI
-----END PRIVATE KEY-----