# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PushNotificationPOC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PushNotificationPOC
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'

  target 'PushNotificationPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PushNotificationPOC-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PushNotificationPOC-tvOS

  target 'PushNotificationPOC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

